<?php
/**
  @file: rusa_member.module

*/

/**
 * hook_preprocess_table
 *
 * We need this to hide the column for a hidden form value.
 *
 * 2025-01-31 - PL - I don't belive this hook is eligable for the upgrade
 * to the src/Hook/Class yet
 * - https://www.drupal.org/node/3442349#hook_convert
 */
function rusa_member_preprocess_table(&$variables) {
    if (isset($variables['attributes']['id'])){
        if( $variables['attributes']['id'] == 'edit-event-data') {
            foreach ($variables['rows'] as $key => &$row ) {
                foreach ( $row['cells'] as &$cell ) {
                    if ( $cell['content']['#type'] == 'hidden' ) {
                        $cell['attributes']['hidden'] = TRUE;
                        $cell['attributes']['aria-hidden'] = 'true';
                        $cell['tag'] = 'span';
                    }
                }
            }
        }
    }
}

